### ISSUE TITLE
GOPATH with multiple path seam to break it

### ISSUE THREAD

**Issue by chmike** [rpeshkov/vscode-go-tests-outline#19]
Your test outline seam to be a great package. Unfortunately I have the impression that it can't deal with GOPATH containing multiple paths. 

When I start VSCode I get the error 

    ENOENT: no such file or directory, open '/home/xxx/.gvm/pkgsets/go1.8.3/global:/home/xxx/Sources/go/src/project/archive/fifo_test.go'

The file exist. I would be interested to use your package because it speedup tests and this is good for TDD.

**Comment by rpeshkov** [comment]
Hi @chmike, thanks for the issue! I'll check it and will let you when it fixed.

**Comment by rpeshkov** [comment]
@chmike, I've uploaded new version of extension to marketplace. This issue is fixed there. Could you please update the extension and check that all good?

**Comment by chmike** [comment]
I've updated it, but GO TESTS doesn't seam to work.
This issue seam to be fixed though. 

The panel GO TESTS remains empty. 
When I click on the right arrow, I get the following error: `command 'gotests.launch' not found`. I also get an error if I click the double right green arrow. 
No test function appear in the GO TESTS panel.

**Comment by rpeshkov** [comment]
Hm, that's weird. On my mac it works without any issue.

Can you please share what environment are you using? OS, VSCode version, Go version.

**Comment by rpeshkov** [comment]
Argh, found what causes the problem. It works when I launch the extension in debug mode from VSCode, but published extension doesn't have xregexp package and that's why it's not working.

**Comment by rpeshkov** [comment]
@chmike new version is published. It should work now.

**Comment by chmike** [comment]
It now works perfectly. Great.
