### ISSUE TITLE
Add -race

### ISSUE THREAD

**Issue by natdm** [rpeshkov/vscode-go-tests-outline#20]
Tests should be ran with the `-race` flag, pretty much always. It's the only way I could 'trust' the output. 

Another idea would be to have this read from the settings config with some kind of `gooutline.race: boolean` flag.

**Comment by rpeshkov** [comment]
Hi @natdm. Sorry for such a big delay. I've updated extension so now it's possible to set additional arguments for 'go test'. You can now add `-race` flag with this option in your config (user or workspace):

```
"go-tests-outline.go-test-params": "-race",
```
